matrix add or sub

In [7]:
import numpy
import numpy as np
print(np.__version__)



2.2.4


In [8]:
matrix_a = np.array([[4,5],[3,4]])
matrix_b=np.array([[5,6],[8,9]])
matrix_sum=matrix_a+matrix_b
print("Matrix Addition:\n",matrix_sum)

Matrix Addition:
 [[ 9 11]
 [11 13]]


In [10]:
matrix_diff=matrix_a-matrix_b
print("Matrix Subtraction:\n",matrix_diff)

Matrix Subtraction:
 [[-1 -1]
 [-5 -5]]




#Matrix Multiplication

In [11]:
matrix_mul=matrix_a*matrix_b
print("\n Multiplication:\n",matrix_mul)


 Multiplication:
 [[20 30]
 [24 36]]


In [12]:
matrix_dot=np.dot(matrix_a,matrix_b)
print("\nmatric Dot product\n",matrix_dot)


matric Dot product
 [[60 69]
 [47 54]]


In [13]:

# Transpose of a matrix
transpose_a = np.transpose(matrix_a)
print("\nMatrix Transpose:\n", transpose_a)


Matrix Transpose:
 [[4 3]
 [5 4]]
