In [12]:
import numpy as np
print(np.__version__)
a = np.array(10)#odimensional array
print(a)

a1 =np.array([10,20])#1d
#indexing
print(a1[0:1])
a2=np.array([[10,21],[20,30]])#2d
a2[0][1]
a3 = np.array([[[10,20,30],[10,20,30]],[[50,60,80],[20,50,60]]])#3dimensional array

print(a3[0][1][2])#three dimensional
print(a3)

2.2.4
10
[10]
30
[[[10 20 30]
  [10 20 30]]

 [[50 60 80]
  [20 50 60]]]


In [ ]:
a3 = np.array([[[10,20,30],[10,20,30]],[[50,60,80],[20,50,60]]])#3dimensional array

print(a3[0][1][2])#three dimensional
print(a3)

In [ ]:
a=([[11,12,],[15,16]])
b=np.asarray(a,dtype=float)
print(b)

#row major order("c")///coloum major order("f")

In [ ]:
b=np.asarray(a,dtype=int,order="c")
for i in np.nditer(b):
    print(i)

#from buffer


In [ ]:
a=b"welcome to numpy"
np.frombuffer(a,dtype="S1",count=2)
a=b"welcome to numpy"
np.frombuffer(a,dtype="S1",offset=5)

fromiter()

In [ ]:
a=[12.14,15]
np.fromiter(a,dtype="S1")

Array

In [ ]:
import numpy as np

# Creating a NumPy array of zeros with a size of 3
a = np.zeros(3)
print(a)


In [11]:
import numpy as np

# Creating a 3D NumPy array of zeros with dimensions 2x2x3
a = np.zeros([2, 2, 3])
print(a)


[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [15]:
import numpy as np
# Creating a 3D NumPy array of Full with dimensions 2x2x3
a = np.full([2, 2, 3],2)
print(a)

[[[2 2 2]
  [2 2 2]]

 [[2 2 2]
  [2 2 2]]]


In [17]:
import numpy as np
# Creating a 3D NumPy array of random with dimensions 2x2x3
a = np.random.rand(2, 2, 3)
print(a)

[[[0.33540941 0.55248789 0.56786797]
  [0.58941201 0.54469165 0.53073874]]

 [[0.3694292  0.81677183 0.25895584]
  [0.75087095 0.63216821 0.39711493]]]


In [20]:
import numpy as np
# Creating a 3D NumPy array of ones with dimensions 2x2x3
a = np.ones([2, 2, 3])
print(a)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [23]:
import numpy as np
# Creating a 3D NumPy array of eye with dimensions 2x2x3
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
