In [34]:
import numpy as np
print(np.__version__)
a = np.array(10)#odimensional array
print(a)

a1 =np.array([10,20])#1d
#indexing
print(a1[0:1])
a2=np.array([[10,21],[20,30]])#2d
a2[0][1]
a3 = np.array([[[10,20,30],[10,20,30]],[[50,60,80],[20,50,60]]])#3dimensional array

print(a3[0][1][2])#three dimensional
print(a3)

2.2.4
10
[10]
30
[[[10 20 30]
  [10 20 30]]

 [[50 60 80]
  [20 50 60]]]


In [35]:
a3 = np.array([[[10,20,30],[10,20,30]],[[50,60,80],[20,50,60]]])#3dimensional array

print(a3[0][1][2])#three dimensional
print(a3)

30
[[[10 20 30]
  [10 20 30]]

 [[50 60 80]
  [20 50 60]]]


asarray with nditer

In [36]:
a=([[11,12,],[15,16]])
b=np.asarray(a,dtype=float)
print(b)

[[11. 12.]
 [15. 16.]]


#row major order("c")///coloum major order("f")

In [41]:
b=np.asarray(a,dtype=int,order="c")
for i in np.nditer(b):
    print(i)

11
12
15
16


#from buffer


In [46]:
a=b"welcome to numpy"
np.frombuffer(a,dtype="S1",count=2)
a=b"welcome to numpy"
np.frombuffer(a,dtype="S1",offset=5)

array([b'm', b'e', b' ', b't', b'o', b' ', b'n', b'u', b'm', b'p', b'y'],
      dtype='|S1')

fromiter()

In [48]:
a=[12.14,15]
np.fromiter(a,dtype="S1")

array([b'1', b'1'], dtype='|S1')